# Generated by Django 6.0.3 on 2026-03-30 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_key",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="存储键"
                    ),
                ),
                ("file_url", models.URLField(max_length=1000, verbose_name="访问地址")),
                ("file_size", models.PositiveBigIntegerField(verbose_name="文件大小")),
                ("mime_type", models.CharField(max_length=100, verbose_name="类型")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "附件",
                "verbose_name_plural": "附件",
                "ordering": ["-created_at"],
            },
        ),
    ]
