# Generated by Django 5.2.12 on 2026-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file_key",
            field=models.CharField(max_length=500, unique=True, verbose_name="存储键"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_size",
            field=models.PositiveBigIntegerField(verbose_name="文件大小"),
        ),
    ]
