# Generated by Django 5.2.12 on 2026-03-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_alter_attachment_file_key_alter_attachment_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="issue",
        ),
    ]
