# Generated by Django 6.0.3 on 2026-05-26 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0016_wizard_chat_description_field'),
        ('projects', '0003_projectmember_is_manager'),
        ('tools', '0002_attachment_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITestingModelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner_model', models.CharField(blank=True, max_length=100, verbose_name='Planner 模型')),
                ('critic_model', models.CharField(blank=True, max_length=100, verbose_name='Critic 模型')),
                ('temperature', models.FloatField(default=0.1, verbose_name='Temperature')),
                ('tool_call_timeout_secs', models.PositiveIntegerField(default=60, verbose_name='工具调用超时(秒)')),
                ('max_agent_turns', models.PositiveIntegerField(default=30, verbose_name='最大 Agent 轮次')),
                ('enable_critic_review', models.BooleanField(default=False, verbose_name='启用 Critic 复核')),
                ('is_global_default', models.BooleanField(default=False, verbose_name='全局默认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_settings', to='ai.llmconfig', verbose_name='LLM 配置')),
            ],
            options={
                'verbose_name': 'AI 测试模型设置',
                'verbose_name_plural': 'AI 测试模型设置',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础 URL')),
                ('login_type', models.CharField(choices=[('username_password', '账号密码'), ('saved_session', '已保存会话'), ('none', '无登录')], default='username_password', max_length=50, verbose_name='登录类型')),
                ('login_config', models.JSONField(blank=True, default=dict, verbose_name='登录配置')),
                ('login_username', models.CharField(blank=True, max_length=200, verbose_name='测试账号')),
                ('login_password_encrypted', models.TextField(blank=True, verbose_name='测试密码(加密)')),
                ('credential_ref', models.CharField(blank=True, max_length=200, verbose_name='凭证引用')),
                ('allowed_url_patterns', models.JSONField(blank=True, default=list, verbose_name='URL 白名单')),
                ('allow_write_actions', models.BooleanField(default=False, verbose_name='允许写操作')),
                ('allow_dangerous_actions', models.BooleanField(default=False, verbose_name='允许危险操作')),
                ('artifact_retention_policy', models.JSONField(blank=True, default=dict, verbose_name='产物保留策略')),
                ('max_concurrent_runs', models.PositiveIntegerField(default=1, verbose_name='最大并发执行')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='ai_testing.aitestingmodelsettings', verbose_name='模型设置覆盖')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_environments', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'AI 测试环境',
                'verbose_name_plural': 'AI 测试环境',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='流程名称')),
                ('description', models.TextField(verbose_name='流程描述')),
                ('target_url', models.URLField(blank=True, max_length=500, verbose_name='目标 URL')),
                ('success_criteria', models.TextField(blank=True, verbose_name='成功标准')),
                ('max_steps', models.PositiveIntegerField(default=30, verbose_name='最大步骤数')),
                ('timeout_secs', models.PositiveIntegerField(default=300, verbose_name='超时(秒)')),
                ('cleanup_policy', models.CharField(choices=[('none', '不清理'), ('delete', '删除'), ('close', '关闭')], default='none', max_length=20, verbose_name='清理策略')),
                ('cleanup_enabled', models.BooleanField(default=False, verbose_name='启用自动清理')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_flows', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_flows', to='ai_testing.projectenvironment', verbose_name='默认环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_flows', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'AI 测试流程',
                'verbose_name_plural': 'AI 测试流程',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('target_url', models.URLField(blank=True, max_length=500, verbose_name='目标 URL')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, verbose_name='输入快照')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('final_summary', models.TextField(blank=True, verbose_name='最终摘要')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_runs', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ai_testing.projectenvironment', verbose_name='环境')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai_testing.testflow', verbose_name='流程')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_runs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'AI 测试执行',
                'verbose_name_plural': 'AI 测试执行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('skill_name', models.CharField(blank=True, max_length=100, verbose_name='技能')),
                ('thought_summary', models.TextField(blank=True, verbose_name='决策摘要')),
                ('tool_name', models.CharField(max_length=100, verbose_name='工具名')),
                ('tool_input', models.JSONField(blank=True, default=dict, verbose_name='工具输入')),
                ('tool_result', models.JSONField(blank=True, default=dict, verbose_name='工具输出')),
                ('page_url', models.URLField(blank=True, max_length=1000, verbose_name='页面 URL')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_testing.testrun', verbose_name='执行')),
            ],
            options={
                'verbose_name': 'AI 测试步骤',
                'verbose_name_plural': 'AI 测试步骤',
                'ordering': ['step_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrowserArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('screenshot', '截图'), ('trace', 'Trace'), ('console_log', 'Console 日志'), ('network_log', 'Network 日志'), ('video', '视频')], max_length=30, verbose_name='产物类型')),
                ('content', models.TextField(blank=True, verbose_name='文本内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_artifacts', to='tools.attachment', verbose_name='附件引用')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai_testing.testrun', verbose_name='执行')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='ai_testing.teststeprun', verbose_name='步骤')),
            ],
            options={
                'verbose_name': '浏览器产物',
                'verbose_name_plural': '浏览器产物',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aitestingmodelsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global_default', True)), fields=('is_global_default',), name='unique_ai_testing_global_default'),
        ),
        migrations.AlterUniqueTogether(
            name='projectenvironment',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teststeprun',
            unique_together={('run', 'step_index')},
        ),
    ]
