# Generated by Django 6.0.3 on 2026-05-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ['-created_at'], 'permissions': [('view_ai_testing', 'Can view AI testing pages'), ('manage_ai_testing', 'Can manage AI testing configuration')], 'verbose_name': 'AI 测试执行', 'verbose_name_plural': 'AI 测试执行'},
        ),
    ]
