# Generated by Django 5.2.12 on 2026-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        ("repos", "0004_repo_clone_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repos",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="repos.repo",
                verbose_name="关联仓库",
            ),
        ),
    ]
