# Generated by Django 5.2.12 on 2026-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_migrate_linked_repos_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="linked_repos",
        ),
    ]
