# Generated by Django 6.0.3 on 2026-04-02 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="草稿"),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="目标用户",
            ),
        ),
    ]
