# Generated by Django 6.0.3 on 2026-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False, verbose_name="是否为机器人"),
        ),
    ]
