# Generated by Django 5.2.12 on 2026-03-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="用户设置"),
        ),
    ]
