# Generated by Django 5.2.12 on 2026-03-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=50, verbose_name="头像"),
        ),
    ]
