# Generated by Django 6.0.3 on 2026-04-16 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField(verbose_name="统计起始日期")),
                ("period_end", models.DateField(verbose_name="统计截止日期")),
                (
                    "issue_metrics",
                    models.JSONField(default=dict, verbose_name="问题指标"),
                ),
                (
                    "commit_metrics",
                    models.JSONField(default=dict, verbose_name="Commit 指标"),
                ),
                ("scores", models.JSONField(default=dict, verbose_name="评分")),
                ("rankings", models.JSONField(default=dict, verbose_name="排名")),
                (
                    "suggestions",
                    models.JSONField(default=dict, verbose_name="改进建议"),
                ),
                ("computed_at", models.DateTimeField(verbose_name="计算时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_snapshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI 快照",
                "verbose_name_plural": "KPI 快照",
                "ordering": ["-period_end", "-computed_at"],
                "permissions": [
                    ("view_own_kpi", "Can view own KPI"),
                    ("refresh_kpi", "Can refresh KPI data"),
                ],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
    ]
