# Generated by Django 6.0.3 on 2026-04-17 03:19

import apps.kpi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0002_seed_kpi_periodic_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension_weights",
                    models.JSONField(
                        default=apps.kpi.models._default_dimension_weights,
                        help_text="5 个维度在综合分中的权重，总和应为 1.0",
                        verbose_name="综合分维度权重",
                    ),
                ),
                (
                    "efficiency_formula",
                    models.JSONField(
                        default=apps.kpi.models._default_efficiency_formula,
                        help_text="效率维度各子指标权重",
                        verbose_name="效率评分公式",
                    ),
                ),
                (
                    "output_formula",
                    models.JSONField(
                        default=apps.kpi.models._default_output_formula,
                        help_text="产出维度各子指标权重",
                        verbose_name="产出评分公式",
                    ),
                ),
                (
                    "quality_formula",
                    models.JSONField(
                        default=apps.kpi.models._default_quality_formula,
                        help_text="质量维度各子指标权重",
                        verbose_name="质量评分公式",
                    ),
                ),
                (
                    "capability_formula",
                    models.JSONField(
                        default=apps.kpi.models._default_capability_formula,
                        help_text="能力维度各子指标权重",
                        verbose_name="能力评分公式",
                    ),
                ),
                (
                    "ceilings",
                    models.JSONField(
                        default=apps.kpi.models._default_ceilings,
                        help_text="各指标达到满分 100 的阈值",
                        verbose_name="饱和天花板值",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "KPI 评分规则",
                "verbose_name_plural": "KPI 评分规则",
            },
        ),
    ]
