# Generated by Django 6.0.3 on 2026-04-17 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0003_add_scoring_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_generated", "AI 生成"),
                            ("manager_added", "管理员添加"),
                        ],
                        default="manager_added",
                        max_length=15,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        default="general", max_length=20, verbose_name="KPI 维度"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "measurable_target",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="可量化目标",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="分值"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("in_progress", "进行中"),
                            ("submitted", "已提交"),
                            ("verified", "已验收"),
                            ("not_achieved", "未达成"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "quality_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="完成质量系数",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "行动项",
                "verbose_name_plural": "行动项",
                "ordering": ["sort_order", "-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItemComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "attachment_url",
                    models.URLField(blank=True, default="", verbose_name="附件 URL"),
                ),
                (
                    "attachment_key",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="附件 Key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="kpi.actionitem",
                        verbose_name="行动项",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "行动项评论",
                "verbose_name_plural": "行动项评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="格式: 2026-04", max_length=7, verbose_name="月度周期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草案"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source_kpi_scores",
                    models.JSONField(default=dict, verbose_name="KPI 评分快照"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归档时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "提升计划",
                "verbose_name_plural": "提升计划",
                "ordering": ["-period", "-created_at"],
                "permissions": [("view_own_plan", "Can view own improvement plan")],
                "unique_together": {("user", "period")},
            },
        ),
        migrations.AddField(
            model_name="actionitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_items",
                to="kpi.improvementplan",
                verbose_name="所属计划",
            ),
        ),
    ]
