# Generated by Django 6.0.3 on 2026-06-03 03:39

import apps.kpi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0007_add_workload_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpiscoringconfig",
            name="review_dimensions",
            field=models.JSONField(
                default=apps.kpi.models._default_review_dimensions,
                help_text="点评维度候选库/默认池，每项 {key,label,weight}；派发新任务时默认从此填充，之后逐任务可改",
                verbose_name="点评维度库",
            ),
        ),
    ]
