# Generated by Django 6.0.3 on 2026-06-03 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0008_kpiscoringconfig_review_dimensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="截止日期"),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="review_comment",
            field=models.TextField(blank=True, default="", verbose_name="总评"),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="review_dimensions",
            field=models.JSONField(blank=True, default=list, verbose_name="本任务维度"),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="评分时间"),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评分人",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="scores",
            field=models.JSONField(blank=True, default=dict, verbose_name="维度评分"),
        ),
    ]
