# Generated by Django 6.0.3 on 2026-06-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0012_actionitem_self_eta_actionitem_start_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='员工已确认'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='kpi.actionitem', verbose_name='顺延自'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='improve_note',
            field=models.TextField(blank=True, default='', verbose_name='改进措施'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='not_achieved_reason',
            field=models.CharField(blank=True, choices=[('ability', '能力/方法不足'), ('effort', '投入/主动性不够'), ('unrealistic', '目标不合理'), ('blocked', '外部阻塞'), ('reprioritized', '优先级调整')], default='', max_length=20, verbose_name='未达成归因'),
        ),
    ]
