# Generated by Django 6.0.3 on 2026-03-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="路由路径"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                (
                    "show_in_nav",
                    models.BooleanField(default=True, verbose_name="显示在导航栏"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="seed = sync command, manual = UI",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_routes",
                        to="auth.permission",
                        verbose_name="所需权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "页面路由",
                "verbose_name_plural": "页面路由",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
