# Generated by Django 5.2.12 on 2026-03-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="名称"),
                ),
                ("api_key", models.CharField(max_length=500, verbose_name="API Key")),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Base URL"
                    ),
                ),
                (
                    "supports_json_mode",
                    models.BooleanField(default=True, verbose_name="支持 JSON 模式"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认配置"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM 配置",
                "verbose_name_plural": "LLM 配置",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="标识符"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="显示名")),
                ("system_prompt", models.TextField(verbose_name="系统提示词")),
                (
                    "user_prompt_template",
                    models.TextField(verbose_name="用户提示词模板"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="模型")),
                (
                    "temperature",
                    models.FloatField(default=0.3, verbose_name="Temperature"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="留空时使用默认配置",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.llmconfig",
                        verbose_name="LLM 配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词",
                "verbose_name_plural": "提示词",
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(max_length=100, verbose_name="分析类型"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("page_open", "页面打开"), ("manual", "手动刷新")],
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("done", "完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="数据哈希"
                    ),
                ),
                (
                    "input_context",
                    models.JSONField(default=dict, verbose_name="输入上下文"),
                ),
                (
                    "prompt_snapshot",
                    models.JSONField(default=dict, verbose_name="提示词快照"),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="LLM 原始回包"
                    ),
                ),
                (
                    "parsed_result",
                    models.JSONField(blank=True, null=True, verbose_name="解析结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发用户",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.prompt",
                        verbose_name="提示词模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 分析",
                "verbose_name_plural": "AI 分析",
                "ordering": ["-created_at"],
            },
        ),
    ]
