# Generated by Django 5.2.12 on 2026-03-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="model",
            new_name="llm_model",
        ),
    ]
