# Generated by Django 5.2.12 on 2026-03-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_rename_prompt_model_to_llm_model"),
        ("issues", "0004_issue_repo_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="issues.issue",
                verbose_name="关联问题",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("page_open", "页面打开"),
                    ("manual", "手动刷新"),
                    ("auto", "自动触发"),
                ],
                max_length=20,
                verbose_name="触发方式",
            ),
        ),
    ]
