# Generated by Django 6.0.3 on 2026-03-30 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("repos", "0001_initial"),
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "紧急"),
                            ("P1", "高"),
                            ("P2", "中"),
                            ("P3", "低"),
                        ],
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="状态")),
                (
                    "labels",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "estimated_completion",
                    models.DateField(blank=True, null=True, verbose_name="预计完成"),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="实际工时",
                    ),
                ),
                ("cause", models.TextField(blank=True, verbose_name="原因分析")),
                ("solution", models.TextField(blank=True, verbose_name="解决办法")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="issues",
                        to="tools.attachment",
                        verbose_name="附件",
                    ),
                ),
                (
                    "github_issues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="devtrack_issues",
                        to="repos.githubissue",
                        verbose_name="关联 GitHub Issues",
                    ),
                ),
                (
                    "helpers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="helped_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="协助人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="projects.project",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="repos.repo",
                        verbose_name="关联仓库",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提出人",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
                "ordering": ["-created_at"],
                "permissions": [
                    ("batch_update_issue", "Can batch update issues"),
                    ("view_dashboard", "Can view dashboard"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="动作")),
                (
                    "detail",
                    models.CharField(blank=True, max_length=200, verbose_name="详情"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动记录",
                "verbose_name_plural": "活动记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
