# Generated by Django 5.2.12 on 2026-03-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="动作")),
                (
                    "detail",
                    models.CharField(blank=True, max_length=200, verbose_name="详情"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "活动记录",
                "verbose_name_plural": "活动记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("priority", models.CharField(max_length=10, verbose_name="优先级")),
                ("status", models.CharField(max_length=20, verbose_name="状态")),
                (
                    "labels",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "estimated_completion",
                    models.DateField(blank=True, null=True, verbose_name="预计完成"),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="实际工时",
                    ),
                ),
                ("cause", models.TextField(blank=True, verbose_name="原因分析")),
                ("solution", models.TextField(blank=True, verbose_name="解决办法")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-created_at"],
                "permissions": [
                    ("batch_update_issue", "Can batch update issues"),
                    ("view_dashboard", "Can view dashboard"),
                ],
            },
        ),
    ]
