# Generated by Django 6.0.3 on 2026-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="source",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="来源"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_meta",
            field=models.JSONField(blank=True, null=True, verbose_name="来源元数据"),
        ),
    ]
