# Generated by Django 5.2.12 on 2026-03-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
        ("repos", "0003_add_githubissue_state_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("batch_update_issue", "Can batch update issues"),
                    ("view_dashboard", "Can view dashboard"),
                ],
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="github_issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="devtrack_issues",
                to="repos.githubissue",
                verbose_name="关联 GitHub Issues",
            ),
        ),
    ]
