# Generated by Django 5.2.12 on 2026-03-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_add_github_issues_m2m"),
        ("repos", "0004_repo_clone_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="repos.repo",
                verbose_name="关联仓库",
            ),
        ),
    ]
