# Generated by Django 6.0.3 on 2026-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_rename_reporter_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="已删除"),
        ),
    ]
