# Generated by Django 6.0.3 on 2026-04-22 10:02

from django.db import migrations, models


def rename_backlog_to_unplanned(apps, schema_editor):
    Issue = apps.get_model("issues", "Issue")
    Issue.objects.filter(status="积压").update(status="未计划")


def rename_unplanned_to_backlog(apps, schema_editor):
    Issue = apps.get_model("issues", "Issue")
    Issue.objects.filter(status="未计划").update(status="积压")


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_issue_deleted_at_issue_is_deleted"),
    ]

    operations = [
        migrations.RunPython(rename_backlog_to_unplanned, rename_unplanned_to_backlog),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("未计划", "未计划"),
                    ("待处理", "待处理"),
                    ("进行中", "进行中"),
                    ("已解决", "已解决"),
                    ("已发布", "已发布"),
                    ("已关闭", "已关闭"),
                ],
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
