# Generated by Django 5.2.12 on 2026-03-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_issue_repo_fk"),
        ("tools", "0003_remove_issue_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="tools.attachment",
                verbose_name="附件",
            ),
        ),
    ]
