# Generated by Django 5.2.12 on 2026-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_add_helpers_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("P0", "紧急"), ("P1", "高"), ("P2", "中"), ("P3", "低")],
                max_length=10,
                verbose_name="优先级",
            ),
        ),
    ]
