# Generated by Django 5.2.12 on 2026-03-20 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名")),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="完整名称"),
                ),
                ("url", models.URLField(verbose_name="GitHub URL")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "default_branch",
                    models.CharField(
                        default="main", max_length=50, verbose_name="默认分支"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="主要语言"
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(default=0, verbose_name="Star 数"),
                ),
                (
                    "status",
                    models.CharField(
                        default="在线", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
            ],
            options={
                "verbose_name": "GitHub 仓库",
                "verbose_name_plural": "GitHub 仓库",
                "ordering": ["-connected_at"],
            },
        ),
    ]
