# Generated by Django 6.0.3 on 2026-03-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名")),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="完整名称"),
                ),
                ("url", models.CharField(max_length=500, verbose_name="GitHub URL")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "default_branch",
                    models.CharField(
                        default="main", max_length=50, verbose_name="默认分支"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="主要语言"
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(default=0, verbose_name="Star 数"),
                ),
                (
                    "status",
                    models.CharField(
                        default="在线", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "github_token",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="GitHub Token"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近同步时间"
                    ),
                ),
                (
                    "clone_status",
                    models.CharField(
                        choices=[
                            ("not_cloned", "未克隆"),
                            ("cloning", "克隆中"),
                            ("cloned", "已克隆"),
                            ("failed", "失败"),
                            ("error", "错误"),
                        ],
                        default="not_cloned",
                        max_length=20,
                        verbose_name="克隆状态",
                    ),
                ),
                (
                    "clone_error",
                    models.TextField(blank=True, verbose_name="克隆错误信息"),
                ),
                (
                    "current_branch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="当前分支"
                    ),
                ),
                (
                    "cloned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="克隆时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub 仓库",
                "verbose_name_plural": "GitHub 仓库",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_id",
                    models.PositiveIntegerField(verbose_name="GitHub Issue 编号"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                ("body", models.TextField(blank=True, verbose_name="内容")),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "开放"), ("closed", "已关闭")],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("labels", models.JSONField(default=list, verbose_name="标签")),
                ("assignees", models.JSONField(default=list, verbose_name="负责人")),
                (
                    "github_created_at",
                    models.DateTimeField(verbose_name="GitHub 创建时间"),
                ),
                (
                    "github_updated_at",
                    models.DateTimeField(verbose_name="GitHub 更新时间"),
                ),
                (
                    "github_closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="GitHub 关闭时间"
                    ),
                ),
                ("synced_at", models.DateTimeField(verbose_name="同步时间")),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_issues",
                        to="repos.repo",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Issue",
                "verbose_name_plural": "GitHub Issues",
                "ordering": ["-github_created_at"],
                "unique_together": {("repo", "github_id")},
            },
        ),
    ]
