# Generated by Django 5.2.12 on 2026-03-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="github_token",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="GitHub Token"
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近同步时间"
            ),
        ),
        migrations.CreateModel(
            name="GitHubIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_id",
                    models.PositiveIntegerField(verbose_name="GitHub Issue 编号"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                ("body", models.TextField(blank=True, verbose_name="内容")),
                ("state", models.CharField(max_length=20, verbose_name="状态")),
                ("labels", models.JSONField(default=list, verbose_name="标签")),
                ("assignees", models.JSONField(default=list, verbose_name="负责人")),
                (
                    "github_created_at",
                    models.DateTimeField(verbose_name="GitHub 创建时间"),
                ),
                (
                    "github_updated_at",
                    models.DateTimeField(verbose_name="GitHub 更新时间"),
                ),
                (
                    "github_closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="GitHub 关闭时间"
                    ),
                ),
                ("synced_at", models.DateTimeField(verbose_name="同步时间")),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_issues",
                        to="repos.repo",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Issue",
                "verbose_name_plural": "GitHub Issues",
                "ordering": ["-github_created_at"],
                "unique_together": {("repo", "github_id")},
            },
        ),
    ]
