# Generated by Django 6.0.3 on 2026-04-01 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=40, verbose_name="提交哈希")),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="作者名"),
                ),
                (
                    "author_email",
                    models.CharField(max_length=254, verbose_name="作者邮箱"),
                ),
                ("date", models.DateTimeField(verbose_name="提交时间")),
                ("message", models.TextField(verbose_name="提交信息")),
                ("additions", models.IntegerField(default=0, verbose_name="新增行数")),
                ("deletions", models.IntegerField(default=0, verbose_name="删除行数")),
                (
                    "files_changed",
                    models.JSONField(default=list, verbose_name="变更文件"),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="repos.repo",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录",
                "ordering": ["-date"],
                "unique_together": {("repo", "hash")},
            },
        ),
        migrations.CreateModel(
            name="GitAuthorAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_email",
                    models.CharField(max_length=254, verbose_name="作者邮箱"),
                ),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="作者名"),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_aliases",
                        to="repos.repo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="git_aliases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git 作者映射",
                "verbose_name_plural": "Git 作者映射",
                "unique_together": {("repo", "author_email")},
            },
        ),
    ]
