# Generated by Django 5.2.12 on 2026-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="url",
            field=models.CharField(max_length=500, verbose_name="GitHub URL"),
        ),
    ]
