# Generated by Django 5.2.12 on 2026-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0002_repo_github_token_repo_last_synced_at_githubissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubissue",
            name="state",
            field=models.CharField(
                choices=[("open", "开放"), ("closed", "已关闭")],
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
