# Generated by Django 5.2.12 on 2026-03-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0003_add_githubissue_state_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="clone_error",
            field=models.TextField(blank=True, verbose_name="克隆错误信息"),
        ),
        migrations.AddField(
            model_name="repo",
            name="clone_status",
            field=models.CharField(
                choices=[
                    ("not_cloned", "未克隆"),
                    ("cloning", "克隆中"),
                    ("cloned", "已克隆"),
                    ("error", "错误"),
                ],
                default="not_cloned",
                max_length=20,
                verbose_name="克隆状态",
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="cloned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="克隆时间"),
        ),
        migrations.AddField(
            model_name="repo",
            name="current_branch",
            field=models.CharField(blank=True, max_length=100, verbose_name="当前分支"),
        ),
    ]
