# Generated by Django 6.0.3 on 2026-03-30 23:52

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        default=apps.settings.models.default_labels,
                        verbose_name="Issue 标签",
                    ),
                ),
                (
                    "priorities",
                    models.JSONField(
                        default=apps.settings.models.default_priorities,
                        verbose_name="优先级选项",
                    ),
                ),
                (
                    "issue_statuses",
                    models.JSONField(
                        default=apps.settings.models.default_issue_statuses,
                        verbose_name="Issue 状态选项",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
            },
        ),
    ]
