# Generated by Django 6.0.3 on 2026-05-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember_is_manager'),
        ('settings', '0008_status_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='default_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='默认负责人'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='project',
            field=models.ForeignKey(blank=True, help_text='留空表示站点级 key(只可用于站点级接口,例如发布通知)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
        ),
    ]
